name: Build Android
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Node 20 (Requis par Capacitor)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # CORRECTION ICI : On passe Ã  Java 21
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Installation & Sync
        run: |
          npm install
          npx cap sync

      - name: Build APK
        run: cd android && chmod +x gradlew && ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: neurya-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
