name: Build Android
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Node 20
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Java 21 (Celui qui marche !)
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Installation & Sync
        run: |
          npm install
          npx cap sync

      # --- CORRECTION DU CONFLIT KOTLIN ---
      # On injecte une rÃ¨gle pour forcer l'usage d'une seule version
      - name: Patch Kotlin Conflict
        run: |
          echo "
          configurations.all {
              resolutionStrategy {
                  force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
                  force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
              }
          }
          " >> android/app/build.gradle

      - name: Build APK
        run: cd android && chmod +x gradlew && ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: neurya-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
